window.BDX_VENDOR={l:'http://www.biddingx.com?utm_campaign=jiaobiao&%%BDX_EXT%%'};
(function(n,r){function y(a){try{var c="_bdxlog_"+ +new Date+Math.floor(1E5*Math.random()),b=n[c]=new Image;b.onload=b.onerror=function(){n[c]=H};b.src=a}catch(d){try{r.createElement("img").src=a}catch(g){}}}function C(e,c){a.ssl||y(J+e+"&n="+z(c.name)+"&m="+z(c.message)+"&s="+z(c.stack&&String(c.stack).slice(0,200)))}function K(a){var c={quality:"high",align:"middle",menu:"false",wmode:"transparent"},b;for(b in a)a.hasOwnProperty(b)&&(c[b]=a[b]);var d='<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" type="application/x-shockwave-flash" ',
g='<embed src="'+c.swf+'" type="application/x-shockwave-flash" ',h='<param name="movie" value="'+c.swf+'">';c.swf=H;for(b in c)c[b]!==H&&(a=b+'="'+c[b]+'" ',0>",width,height,hspace,vspace,align,class,id,name,style,".indexOf(","+b+",")?h+='<param name="'+b+'" value="'+c[b]+'">':d+=a,g+=a);return d+">"+h+g+"></embed></object>"}function A(e){return e.replace(/%%BDX_EXT%%/g,a.bdx_ext).replace(/%%BDX_WIDTH%%/g,a.width).replace(/%%BDX_HEIGHT%%/g,a.height).replace(/%%BDX_EXT_ENC%%/g,z(a.bdx_ext)).replace(/%%BDX_HOST%%/g,
B)}function L(e){return e.replace(/\{\$(\w+)\}/g,function(c,b){return a[b]||""})}function S(e){if("c"==e){var c;(c=a.end)&&y(A(c).replace(/_JS_/g,1));if(c=a.click_track)for(e=c.length;0<e--;)y(A(c[e]).replace(/_JS_/g,1))}}function M(){try{for(var e;!e||n[e]||document.getElementById(e);)a.id=e="BDX"+Math.round((new Date).getTime()*Math.random());var c=a.logo,c=0<=c&&4>c?[1,0,3,2][c]:-1,b=s.hasOwnProperty(N)?s[N]:0;b&&(t=B+(s.hasOwnProperty("v")?s.v:void 0)+"/"+O,b[c]||(c=-1));a.link=s.hasOwnProperty("l")?
s.l:"http://www.biddingx.com";a.about=s.hasOwnProperty("t")?s.t:"Biddingx.com\u63d0\u4f9b\u7684\u5e7f\u544a";var d=a.container&&document.getElementById(a.container),b="",g=["","{padding:0;margin:0;position:relative;width:{$width}px;height:{$height}px;overflow:hidden;}","-clk {z-index:10;position:absolute;top:0;left:0;width:{$width}px;height:{$height}px;display:block;filter:alpha(opacity=0);opacity:0;background:#FFF;}","-vp {z-index:1;position:relative;padding:0;margin:0;width:{$width}px;height:{$height}px;}"];
-1!=c&&(g.push("-logo {z-index:20;display:block;position:absolute;{$pos};width:"+T+"px;height:"+U+"px;text-indent:90em;overflow:hidden;outline:0;blr:expression(this.onFocus=this.blur());}","-logo:hover {width:"+V+"px;cursor:pointer;}","-logo "+'{background:url("{u}") no-repeat;_background:none;filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(src="{u}");}'.replace(/\{u\}/g,"{$sLogo}"),"-logo:hover "+'{background:url("{u}") no-repeat;_background:none;filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(src="{u}");}'.replace(/\{u\}/g,
"{$bLogo}")),a.sLogo=t+c+"s.png",a.bLogo=t+c+"b.png",a.pos=["left:0;top:0","top:0;right:0","right:0;bottom:0","bottom:0;left:0"][c]);g=g.join("\n."+e);if(d&&document.body){var g=L(g),h=document.createElement("style");h.type="text/css";h.styleSheet?h.styleSheet.cssText+=g:h.innerHTML+=g;document.body.appendChild(h)}else b="<style>"+g+"</style>";var h={html:4,mv:-2,swf:1,flv:2,img:3,png:3,gif:3,jpg:3,jpeg:3},k=a.type||a.url.split(".").pop().toLowerCase(),I=a.ct||h[k]||0;if(k=a.end)a.end=a.click,a.click=
k;n[e]=S;0<I&&(b+='<a class="{$id}-clk" target="_blank" href="{$click}" onclick="try{{$id}(\'c\')}catch(e){}"></a>');-1!=c&&(b+='<a href="{$link}" target="_blank" class="{$id}-logo" title="{$about}">{$about}</a>');a.mark=a.mark||1;-1!=a.mark&&(b+='<img src="'+(B+"/data/v/res/m"+a.mark+".png")+'" style="position:absolute;left:0;bottom:0;z-index:2;"/>');1>5*Math.random()&&(b+='<div style="position:absolute;top:-1000px;">'+K({swf:"{$base}/ui/fc.swf",width:1,height:1})+"</div>");var c='<div id="{$id}" class="{$id}">'+
b,l=a.url,k='<div class="{$id}-vp" id="{$id}VP">';switch(I){case 1:k+=K({swf:l,width:a.width,height:a.height});break;case 2:case -2:k+=K({swf:W,flashvars:"video="+z(l)+"&amp;clickTAG="+z(a.click),scale:"noscale",width:a.width,height:a.height});break;case 3:k+='<img src="{$url}" width="{$width}" height="{$height}" border="0"/>';break;default:a.url=-1===I?"about:blank":a.url+("#"+a.click),k+='<iframe id="{$id}IF" src="{$url}" width="{$width}" height="{$height}" scrolling="no" border="0" frameborder="0" style="border:none;" marginheight="0" marginwidth="0" allowtransparency="true"></iframe>'}var b=
c+(k+"</div>")+"</div>",f="CSS1Compat"!==r.compatMode&&r.body?r.body:r.documentElement,q=f&&f.clientHeight||0,p=f&&f.clientWidth||0,m=a.width,P=a.height;0>=m&&(m=-m,a.width=m||p);0>=P&&(a.height=-P||q);b=A(L(b));d?d.innerHTML+=b:r.write(b);Q&&r.close();b=document.getElementById(e);0<p&&b.clientWidth>p&&(b.style.cssText+=";-webkit-transform-origin: left top;-webkit-transform: scale("+p/m+");");if(-1==I)if(b=document.getElementById(e+"IF")){var u=A(a.adm);try{f=b.contentDocument,f.write(u),f.close()}catch(x){try{f=
b.contentWindow.document,f.write(u),f.close()}catch(v){C(49,v)}}}else y(J+"997&n=iframe_not_found&"+R);X(n,document.getElementById(a.id),a.bdx_ext,a.ssl,y)}catch(w){C(0,w)}}function X(a,c,b,d,g){var h=(d?"https":"http")+"://ana.masky.biddingx.com/masky/ana/ex/e.gif?",k=10;if(b&&c)var r=setInterval(function(){try{for(var l=c,f=a,q=l.offsetParent,p=0,m=l.clientWidth,d=0,u=l.clientHeight,s=l.clientWidth*l.clientHeight,v=0,w=0,n=!0,y=1;q;){var x=l.clientWidth,z=l.clientHeight,B=l.offsetTop,t=q.clientWidth,
A=q.clientHeight,C=q.scrollTop,v=l.offsetLeft-q.scrollLeft,w=B-C,D=0,E=0,F=0,G=0;v>t?D=t:0<v&&(D=v);w>A?E=A:0<w&&(E=w);v+x>t?F=t:0<v+x&&(F=v+x);w+z>A?G=A:0<w+z&&(G=w+z);if(E>=G||D>=F){n=!1;break}if((G-E)*(F-D)<s/2){n=!1;break}p+=v;0>p?p=0:p<D&&(p=D);m+=v;0>m?m=0:F<m&&(m=F);d+=w;0>d?d=0:d<E&&(d=E);u+=w;0>u?u=0:G<u&&(u=G);if(d>=u||p>=m){n=!1;break}if((u-d)*(m-p)<s/2){n=!1;break}l=q;q=l.offsetParent;!q&&y&&(f.top!=f?(q=f.frameElement,f=f.parent):(q=f.document.documentElement,--y))}n&&!--k&&(g(h+b+"&vb=1"),
clearInterval(r))}catch(H){g(h+b+"&vb=9"),clearInterval(r)}},200)}var O="t",N="o",T=24,V=130,U=18,W="{$base}/ui/player.swf",H,z=encodeURIComponent,J="http://c41.clicki.cn/e.gif?p=",a=n.BDX_INFO,R=+new Date;if(!a)return y(J+"998&n=no_info&"+R),!1;var B="http://stuff.cdn.biddingx.com",t=a.base;t&&(B=t.split("/",3).join("/"));a.base=B;var t=B+"/main/script/resource/"+O+"/",s=n.BDX_VENDOR||{},Q=0;try{var x=a.track;if(x)for("string"==typeof x&&(x=[x]);x.length;)y(A(x.shift()).replace(/_JS_/g,1));else C(2,
{name:"no_track_info"})}catch(Y){C("imp_dbg",Y)}r.body?M():(Q=1,setTimeout(M,10))})(window,document);
